# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []
exec-on-workspace-change = [
    '/bin/bash',
    '-c',
    'sketchybar --trigger aerospace_workspace_change AEROSPACE_FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE AEROSPACE_PREV_WORKSPACE=$AEROSPACE_PREV_WORKSPACE',
]

start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 200
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
automatically-unhide-macos-hidden-apps = true

[[on-window-detected]]
if.app-id = 'com.objective-see.lulu.app'
run = 'layout floating'

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 6
inner.vertical = 6
outer.left = 6
outer.bottom = 6
outer.top = 46
outer.right = 6

[mode.main.binding]
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

cmd-alt-ctrl-h = 'focus left'
cmd-alt-ctrl-j = 'focus down'
cmd-alt-ctrl-k = 'focus up'
cmd-alt-ctrl-l = 'focus right'

cmd-alt-ctrl-shift-h = 'move left'
cmd-alt-ctrl-shift-j = 'move down'
cmd-alt-ctrl-shift-k = 'move up'
cmd-alt-ctrl-shift-l = 'move right'

cmd-alt-ctrl-1 = 'workspace 1'
cmd-alt-ctrl-2 = 'workspace 2'
cmd-alt-ctrl-3 = 'workspace 3'
cmd-alt-ctrl-4 = 'workspace 4'
cmd-alt-ctrl-5 = 'workspace 5'
cmd-alt-ctrl-6 = 'workspace 6'
cmd-alt-ctrl-7 = 'workspace 7'
cmd-alt-ctrl-8 = 'workspace 8'
cmd-alt-ctrl-9 = 'workspace 9'

cmd-alt-ctrl-shift-1 = 'move-node-to-workspace 1'
cmd-alt-ctrl-shift-2 = 'move-node-to-workspace 2'
cmd-alt-ctrl-shift-3 = 'move-node-to-workspace 3'
cmd-alt-ctrl-shift-4 = 'move-node-to-workspace 4'
cmd-alt-ctrl-shift-5 = 'move-node-to-workspace 5'
cmd-alt-ctrl-shift-6 = 'move-node-to-workspace 6'
cmd-alt-ctrl-shift-7 = 'move-node-to-workspace 7'
cmd-alt-ctrl-shift-8 = 'move-node-to-workspace 8'
cmd-alt-ctrl-shift-9 = 'move-node-to-workspace 9'

alt-t = 'exec-and-forget open -a "Ghostty"'
alt-f = 'exec-and-forget open -a "Finder"'
alt-w = 'exec-and-forget open -a "Brave Browser"'
alt-z = 'exec-and-forget open -a "Zed"'
alt-y = 'exec-and-forget open -a "FreeTube"'
alt-s = 'exec-and-forget open -a "Signal"'
alt-m = 'exec-and-forget open -a "Deezer"'
alt-d = 'exec-and-forget open -a "Element"'
alt-n = 'exec-and-forget open -a "Notesnook"'

alt-shift-r = 'mode resize'
alt-shift-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
ctrl-h = ['join-with left']
ctrl-j = ['join-with down']
ctrl-k = ['join-with up']
ctrl-l = ['join-with right']

[mode.resize.binding]
h = 'resize smart -20'
l = 'resize smart +20'
j = 'resize height +20'
k = 'resize height -20'
esc = 'mode main'
